---
name: Pester Report

on:
  workflow_run:
    workflows: [Pester]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: Pester-Results
          name: Pester Tests
          path: '*.xml'
          reporter: jest-junit
