name: Publish Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release asset
        run: |
          shopt -s extglob
          name="VeeamNotify-$GITHUB_REF_NAME"
          mkdir "$name"
          cp -rv !($name) $name/
          zip -r "$name.zip" "./$name" -x "./$name/.*/*" "./$name/.*" "./$name/*/.gitkeep" "./$name/asset/*" "./$name/tests/*" "./$name/README.md"
          rm -r "$name"

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: VeeamNotify-${{ github.ref_name }}.zip
          name: "Release ${{ github.ref_name }}"
